import React,{useEffect,useState} from 'react';
import {View,Text,StyleSheet,ScrollView,Pressable,TextInput,Image,Modal,Alert} from 'react-native';
import {Ionicons} from '@expo/vector-icons';

const API='http://localhost:3000/api';
const demo=[
{name:'Maya Chen',handle:'@mayachen',time:'12m',text:'The future of social is not louder. It is smarter — better conversations, better communities, and more control for people.',likes:'2.8K',replies:'184',reposts:'521',img:'https://i.pravatar.cc/100?img=47'},
{name:'Jordan Okafor',handle:'@jordanokafor',time:'34m',text:'Just shipped something I have been building for months. The feeling when an idea finally becomes real is unmatched. 🚀',likes:'1.4K',replies:'96',reposts:'207',img:'https://i.pravatar.cc/100?img=12'},
{name:'NovaPulse',handle:'@novapulse',time:'1h',text:'Welcome to a new era of conversation. Discover ideas, build communities and share what matters.',likes:'8.9K',replies:'412',reposts:'1.8K',img:'https://i.pravatar.cc/100?img=5'}];
function Icon({name,size=22}){return <Ionicons name={name as any} size={size} color="#A9B1C6"/>}
function Post({p,onAction}){const [liked,setLiked]=useState(!!p.liked);const [reposted,setReposted]=useState(false);const [book,setBook]=useState(!!p.bookmarked);
return <View style={s.post}><Image source={{uri:p.avatar||p.img}} style={s.avatar}/><View style={{flex:1}}>
<View style={s.row}><Text style={s.name}>{p.name}</Text><Text style={s.handle}> {p.handle} · {p.time||'now'}</Text><Icon name="ellipsis-horizontal" size={18}/></View>
<Text style={s.text}>{p.body||p.text}</Text><View style={s.actions}>
<Pressable style={s.act}><Icon name="chatbubble-outline" size={18}/><Text style={s.count}>{p.replies||0}</Text></Pressable>
<Pressable style={s.act} onPress={()=>{setReposted(!reposted);onAction?.(p.id,'repost')}}><Icon name={reposted?'repeat':'repeat-outline'} size={20}/><Text style={s.count}>{p.reposts||0}</Text></Pressable>
<Pressable style={s.act} onPress={()=>{setLiked(!liked);onAction?.(p.id,'like')}}><Icon name={liked?'heart':'heart-outline'} size={19}/><Text style={[s.count,liked&&{color:'#ff4f87'}]}>{p.likes||0}</Text></Pressable>
<Pressable onPress={()=>{setBook(!book);onAction?.(p.id,'bookmark')}}><Icon name={book?'bookmark':'bookmark-outline'} size={19}/></Pressable><Pressable><Icon name="share-outline" size={19}/></Pressable>
</View></View></View>}
function Nav({icon,label,onPress}){return <Pressable style={s.nav} onPress={onPress}><Icon name={icon}/><Text style={s.navText}>{label}</Text></Pressable>}
export default function Home(){const [tab,setTab]=useState('For You');const [compose,setCompose]=useState(false);const [draft,setDraft]=useState('');const [screen,setScreen]=useState('Home');const [feed,setFeed]=useState<any[]>(demo);const [logged,setLogged]=useState(false);
async function load(){try{const t=globalThis.localStorage?.getItem?.('np_token'); if(!t)return; const r=await fetch(API+'/feed',{headers:{Authorization:'Bearer '+t}});if(r.ok){setFeed(await r.json());setLogged(true)}}catch{}}
useEffect(()=>{load()},[]);
async function action(id,type){try{const t=globalThis.localStorage?.getItem?.('np_token');if(t)await fetch(`${API}/posts/${id}/${type}`,{method:'POST',headers:{Authorization:'Bearer '+t}})}catch{}}
async function publish(){if(!draft.trim())return;try{const t=globalThis.localStorage?.getItem?.('np_token');if(t){await fetch(API+'/posts',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({body:draft})});await load()}}catch{}setDraft('');setCompose(false)}
return <View style={s.root}><View style={s.sidebar}><Text style={s.logo}>N<span>•</span>P</Text>
<Nav icon="home" label="Home" onPress={()=>setScreen('Home')}/><Nav icon="search" label="Explore" onPress={()=>setScreen('Explore')}/><Nav icon="notifications-outline" label="Notifications" onPress={()=>setScreen('Notifications')}/><Nav icon="mail-outline" label="Messages" onPress={()=>setScreen('Messages')}/><Nav icon="people-outline" label="Communities" onPress={()=>setScreen('Communities')}/><Nav icon="bookmark-outline" label="Bookmarks" onPress={()=>setScreen('Bookmarks')}/><Nav icon="person-outline" label="Profile" onPress={()=>setScreen('Profile')}/>
<Pressable style={s.postBtn} onPress={()=>setCompose(true)}><Text style={s.postBtnText}>Post</Text></Pressable><Text style={s.brand}>PRODUCED BY{'\n'}VECTOR'S ELEMENT TECH</Text></View>
<View style={s.feed}><View style={s.mobileHead}><Text style={s.logo}>N<span>•</span>P</Text><Icon name="sparkles" size={22}/></View><View style={s.tabs}><Pressable onPress={()=>setTab('For You')} style={s.tab}><Text style={[s.tabText,tab==='For You'&&s.active]}>For You</Text>{tab==='For You'&&<View style={s.underline}/>}</Pressable><Pressable onPress={()=>setTab('Following')} style={s.tab}><Text style={[s.tabText,tab==='Following'&&s.active]}>Following</Text>{tab==='Following'&&<View style={s.underline}/>}</Pressable></View>
{screen==='Home'?<><Pressable style={s.quick} onPress={()=>setCompose(true)}><Image source={{uri:'https://i.pravatar.cc/100?img=33'}} style={s.smallAvatar}/><Text style={s.placeholder}>What's happening?</Text><View style={s.quickBtn}><Text style={{fontWeight:'800'}}>Post</Text></View></Pressable><ScrollView>{feed.map((p,i)=><Post p={p} key={p.id||i} onAction={action}/>)}</ScrollView></>:<View style={s.empty}><Icon name={screen==='Explore'?'search':'sparkles'} size={48}/><Text style={s.emptyTitle}>{screen}</Text><Text style={s.emptyText}>This NovaPulse experience is ready for the next backend module.</Text></View>}
</View><View style={s.right}><View style={s.search}><Icon name="search" size={18}/><TextInput placeholder="Search NovaPulse" placeholderTextColor="#69728A" style={{flex:1,color:'white'}}/></View><View style={s.card}><Text style={s.cardTitle}>What's happening</Text><Text style={s.topic}>AI & Technology</Text><Text style={s.meta}>24.8K posts</Text><Text style={s.topic}>Creator economy</Text><Text style={s.meta}>18.2K posts</Text><Text style={s.topic}>Future of work</Text><Text style={s.meta}>9.7K posts</Text></View><View style={s.card}><Text style={s.cardTitle}>NovaPulse</Text><Text style={s.meta}>{logged?'Connected to your account':'Demo mode — connect the API to enable accounts'}</Text></View></View>
<Modal transparent visible={compose} animationType="slide"><View style={s.modal}><View style={s.composer}><View style={s.row}><Pressable onPress={()=>setCompose(false)}><Icon name="close" size={24}/></Pressable><Text style={s.composeTitle}>Create post</Text><Pressable style={s.modalPost} onPress={publish}><Text style={{fontWeight:'800'}}>Post</Text></Pressable></View><TextInput autoFocus multiline value={draft} onChangeText={setDraft} placeholder="Share something with the world…" placeholderTextColor="#69728A" style={s.editor}/><View style={s.composeTools}><Icon name="image-outline"/><Icon name="videocam-outline"/><Icon name="happy-outline"/><Icon name="location-outline"/></View></View></View></Modal>
</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#070911',flexDirection:'row'},sidebar:{width:260,borderRightWidth:1,borderColor:'#171C2B',padding:28,gap:8},feed:{width:650,borderRightWidth:1,borderColor:'#171C2B'},right:{width:330,padding:24},logo:{fontSize:32,fontWeight:'900',color:'#F4F7FF',marginBottom:20},row:{flexDirection:'row',alignItems:'center',gap:5},nav:{flexDirection:'row',alignItems:'center',gap:18,paddingVertical:13},navText:{color:'#DCE2F2',fontSize:16,fontWeight:'600'},postBtn:{backgroundColor:'#B9FF5A',padding:14,borderRadius:28,alignItems:'center',marginTop:10},postBtnText:{fontSize:16,fontWeight:'900'},brand:{color:'#566077',fontSize:9,fontWeight:'800',letterSpacing:1.2,marginTop:'auto',lineHeight:16},tabs:{height:58,flexDirection:'row',borderBottomWidth:1,borderColor:'#171C2B'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabText:{color:'#7E879D',fontWeight:'700'},active:{color:'#F4F7FF'},underline:{height:3,width:70,backgroundColor:'#B9FF5A',position:'absolute',bottom:0,borderRadius:3},quick:{flexDirection:'row',alignItems:'center',padding:16,borderBottomWidth:1,borderColor:'#171C2B',gap:12},smallAvatar:{width:38,height:38,borderRadius:20},placeholder:{flex:1,color:'#69728A',fontSize:15},quickBtn:{backgroundColor:'#B9FF5A',paddingHorizontal:16,paddingVertical:9,borderRadius:20},post:{flexDirection:'row',padding:18,borderBottomWidth:1,borderColor:'#171C2B',gap:12},avatar:{width:46,height:46,borderRadius:24},name:{color:'#F4F7FF',fontWeight:'800'},handle:{color:'#69728A'},text:{color:'#DDE3F2',fontSize:15,lineHeight:23,marginTop:8},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:16},act:{flexDirection:'row',alignItems:'center',gap:7},count:{color:'#69728A',fontSize:12},search:{height:44,borderRadius:24,backgroundColor:'#111624',flexDirection:'row',alignItems:'center',paddingHorizontal:15,gap:8},card:{backgroundColor:'#111624',borderRadius:18,padding:20,marginTop:18},cardTitle:{color:'#F4F7FF',fontSize:19,fontWeight:'900',marginBottom:18},topic:{color:'#DCE2F2',fontWeight:'800',marginTop:12},meta:{color:'#69728A',fontSize:12,marginTop:3},mobileHead:{display:'none'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:30},emptyTitle:{color:'#F4F7FF',fontSize:25,fontWeight:'900',marginTop:18},emptyText:{color:'#69728A',textAlign:'center',marginTop:8},modal:{flex:1,backgroundColor:'#000A',justifyContent:'flex-end'},composer:{backgroundColor:'#0E1220',borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,minHeight:330},composeTitle:{color:'#F4F7FF',fontSize:17,fontWeight:'800',flex:1,textAlign:'center'},modalPost:{backgroundColor:'#B9FF5A',paddingHorizontal:15,paddingVertical:8,borderRadius:18},editor:{color:'#F4F7FF',fontSize:18,minHeight:190,textAlignVertical:'top',marginTop:18},composeTools:{flexDirection:'row',gap:24,borderTopWidth:1,borderColor:'#1B2234',paddingTop:16}});
