import React,{useEffect,useRef,useState} from 'react';
import {View,Text,StyleSheet,FlatList,TextInput,Pressable,KeyboardAvoidingView,Platform,Image} from 'react-native';
import {io} from 'socket.io-client';
import {Ionicons} from '@expo/vector-icons';

const API='http://localhost:3000/api'; const WS='http://localhost:3000';
export default function Messages(){
 const [people,setPeople]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [messages,setMessages]=useState<any[]>([]); const [text,setText]=useState('');
 const socket=useRef<any>(null);
 useEffect(()=>{(async()=>{try{const token=globalThis.localStorage?.getItem?.('np_token');if(!token)return;const r=await fetch(API+'/users',{headers:{Authorization:'Bearer '+token}});if(r.ok)setPeople(await r.json());socket.current=io(WS,{auth:{token}});socket.current.on('message:new',(m:any)=>setMessages(x=>x.some(v=>v.id===m.id)?x:[...x,m]));}catch{}})();return()=>socket.current?.disconnect()},[]);
 async function open(p:any){setSelected(p);try{const t=globalThis.localStorage?.getItem?.('np_token');const r=await fetch(API+'/messages/'+p.id,{headers:{Authorization:'Bearer '+t}});if(r.ok)setMessages(await r.json())}catch{}}
 function send(){if(!text.trim()||!selected)return;socket.current?.emit('message:send',{receiverId:selected.id,body:text},(a:any)=>{if(a?.ok)setText('')})}
 return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==='ios'?'padding':undefined}>
 <View style={s.people}><Text style={s.title}>Messages</Text><FlatList data={people} keyExtractor={x=>String(x.id)} renderItem={({item})=><Pressable style={s.person} onPress={()=>open(item)}><Image source={{uri:item.avatar||'https://i.pravatar.cc/100?u='+item.id}} style={s.avatar}/><View><Text style={s.name}>{item.name}</Text><Text style={s.handle}>@{item.handle}</Text></View></Pressable>}/></View>
 <View style={s.chat}>{selected?<><View style={s.chatHead}><Text style={s.name}>{selected.name}</Text><Text style={s.handle}>@{selected.handle}</Text></View><FlatList style={{flex:1}} contentContainerStyle={{padding:18}} data={messages} keyExtractor={x=>String(x.id)} renderItem={({item})=><View style={[s.bubble,item.sender_id===selected.id?s.theirs:s.mine]}><Text style={s.bubbleText}>{item.body}</Text><Text style={s.time}>{new Date(item.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View>}/><View style={s.inputRow}><TextInput value={text} onChangeText={setText} placeholder="Write a message…" placeholderTextColor="#69728A" style={s.input} onSubmitEditing={send}/><Pressable onPress={send} style={s.send}><Ionicons name="arrow-up" size={20} color="#071000"/></Pressable></View></>:<View style={s.empty}><Ionicons name="chatbubbles-outline" size={52} color="#69728A"/><Text style={s.emptyTitle}>Your messages</Text><Text style={s.handle}>Choose someone to start a real-time conversation.</Text></View>}</View>
 </KeyboardAvoidingView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#070911',flexDirection:'row'},people:{width:300,borderRightWidth:1,borderColor:'#171C2B',padding:20},title:{color:'#F4F7FF',fontSize:25,fontWeight:'900',marginBottom:18},person:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:13},avatar:{width:44,height:44,borderRadius:22},name:{color:'#F4F7FF',fontWeight:'800'},handle:{color:'#69728A',marginTop:3},chat:{flex:1},chatHead:{padding:18,borderBottomWidth:1,borderColor:'#171C2B'},bubble:{maxWidth:'75%',padding:12,borderRadius:17,marginBottom:10},mine:{alignSelf:'flex-end',backgroundColor:'#B9FF5A'},theirs:{alignSelf:'flex-start',backgroundColor:'#151B2A'},bubbleText:{color:'#F4F7FF',lineHeight:20},time:{fontSize:9,color:'#69728A',marginTop:4},inputRow:{flexDirection:'row',gap:10,padding:14,borderTopWidth:1,borderColor:'#171C2B'},input:{flex:1,backgroundColor:'#111624',borderRadius:23,color:'#F4F7FF',paddingHorizontal:16,minHeight:46},send:{width:46,height:46,borderRadius:23,backgroundColor:'#B9FF5A',alignItems:'center',justifyContent:'center'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:30},emptyTitle:{color:'#F4F7FF',fontSize:24,fontWeight:'900',marginTop:14}});
